// Package interview turns gaps in a record into questions worth answering.
//
// Backfill can reconstruct where a person was and what they produced, because
// calendars and commit logs already exist. It cannot reconstruct what they
// thought, since nothing recorded that at the time. The only way past that
// ceiling is to ask, and the only questions worth asking are the ones the
// record can prove are missing: a commitment held for years that stopped
// without explanation, a thread that appeared from nowhere, a day where two
// parts of a life collided.
//
// Every question here is derived from arithmetic over the record rather than
// generated by a model, so a question is never asked about something that did
// not happen.
package interview

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"sort"
	"time"

	"github.com/dcadolph/midden/internal/weave"
)

// Kind is the sort of gap a question addresses.
type Kind string

// The kinds of gap worth asking about.
const (
	// KindEnded asks why a long-running thread stopped.
	KindEnded Kind = "ended"
	// KindBegan asks how a new thread came about.
	KindBegan Kind = "began"
	// KindCrossing asks about a day where separate parts of a life met.
	KindCrossing Kind = "crossing"
	// KindGap asks what was happening while the record itself went quiet.
	KindGap Kind = "gap"
)

// Question is one thing the record cannot answer about itself.
type Question struct {
	// ID identifies the question so it is never asked twice.
	ID string
	// Kind is the sort of gap it addresses.
	Kind Kind
	// Prompt is the question as it is put to the person.
	Prompt string
	// Context is the evidence the question rests on, shown alongside it.
	Context string
	// When is the date the question concerns, used to file the answer.
	When time.Time
	// Weight orders questions, heaviest first.
	Weight int
}

// Options tune question generation.
type Options struct {
	// Now is the observation date.
	Now time.Time
	// MinWeight is the smallest thread weight worth asking about, which keeps
	// incidental patterns from producing questions.
	MinWeight int
	// MinSpanDays is how long a thread must have run before its ending is worth
	// explaining. A school-year reminder repeated for a term is logistics, not a
	// commitment, and asking why it stopped mistakes a to-do list for a life.
	MinSpanDays int
}

// DefaultOptions returns generation settings suited to a personal record.
func DefaultOptions(now time.Time) Options {
	return Options{Now: now, MinWeight: 300, MinSpanDays: 180}
}

// Generate builds the questions a record supports, heaviest first, skipping any
// whose ID is already answered.
func Generate(
	threads []weave.Thread,
	crossings []weave.Overlap,
	gaps []weave.Gap,
	answered map[string]bool,
	opts Options,
) []Question {
	var out []Question
	add := func(q Question) {
		if q.ID == "" || answered[q.ID] {
			return
		}
		out = append(out, q)
	}
	for _, t := range threads {
		if t.Weight() < opts.MinWeight {
			continue
		}
		switch t.Status {
		case weave.Ended:
			if t.SpanDays >= opts.MinSpanDays {
				add(endedQuestion(t))
			}
		case weave.Emerging:
			add(beganQuestion(t))
		case weave.Dormant:
			// Between seasons, not over. Nothing to explain.
		case weave.Ongoing:
			// A thread still running is not a gap. Asking about one produces
			// questions about groceries and school holidays, because frequency
			// alone cannot tell a commitment that mattered from a chore that
			// recurred, and a vapid question teaches the person to ignore the
			// prompt entirely.
		}
	}
	for _, c := range crossings {
		add(crossingQuestion(c))
	}
	// One silence per source at most, the longest. Three questions about what is
	// essentially one intermittent quiet stretch is over-asking, and over-asking
	// is how a prompt earns being ignored.
	seenSource := map[string]bool{}
	for _, g := range gaps {
		if seenSource[g.Source] {
			continue
		}
		seenSource[g.Source] = true
		add(gapQuestion(g))
	}
	// Silences are asked first regardless of weight. A gap and a thread are not
	// measured on the same scale, and no arithmetic makes them comparable: one
	// counts occurrences of a commitment, the other counts months of nothing.
	// A stretch of years the record cannot account for is the larger hole, so
	// kind decides the order and weight only breaks ties inside a kind.
	sort.Slice(out, func(i, j int) bool {
		pi, pj := priority(out[i].Kind), priority(out[j].Kind)
		if pi != pj {
			return pi < pj
		}
		if out[i].Weight != out[j].Weight {
			return out[i].Weight > out[j].Weight
		}
		return out[i].ID < out[j].ID
	})
	return out
}

// priority orders the kinds of gap, lowest first.
func priority(k Kind) int {
	switch k {
	case KindGap:
		return 0
	case KindEnded:
		return 1
	case KindCrossing:
		return 2
	case KindBegan:
		return 3
	}
	return 4
}

// endedQuestion asks about a thread that stopped. An ending is the most
// valuable thing to ask about, because it is the one event a person never
// records: there is a last time, and nobody knows it is the last time.
func endedQuestion(t weave.Thread) Question {
	return Question{
		ID:     id(KindEnded, t.Key),
		Kind:   KindEnded,
		Prompt: fmt.Sprintf("%s stopped. What happened?", t.Label),
		Context: fmt.Sprintf("%d times over %s, ending %s. Nothing since, %s ago.",
			t.Count, approxYears(t.SpanDays), t.Last.Format(dateLayout), approxMonths(t.SilentDays)),
		When:   t.Last,
		Weight: t.Weight(),
	}
}

// beganQuestion asks how something new came about.
func beganQuestion(t weave.Thread) Question {
	return Question{
		ID:      id(KindBegan, t.Key),
		Kind:    KindBegan,
		Prompt:  fmt.Sprintf("%s is new. How did that come about?", t.Label),
		Context: fmt.Sprintf("%d times since %s.", t.Count, t.First.Format(dateLayout)),
		When:    t.First,
		Weight:  t.Weight(),
	}
}

// crossingQuestion asks about a day where separate sources both recorded
// something, which is the only place the record can point at a tension it
// cannot explain.
func crossingQuestion(c weave.Overlap) Question {
	day := c.Day.Format(dateLayout)
	total := 0
	for _, n := range c.Counts {
		total += n
	}
	var lines string
	for _, src := range sortedKeys(c.Headlines) {
		lines += fmt.Sprintf("%s: %s (%d)\n", src, c.Headlines[src], c.Counts[src])
	}
	return Question{
		ID:      id(KindCrossing, day),
		Kind:    KindCrossing,
		Prompt:  fmt.Sprintf("On %s two parts of your life ran at once. What was going on?", day),
		Context: lines,
		When:    c.Day,
		Weight:  total,
	}
}

// gapQuestion asks about a stretch where the record fell silent. A silence is
// the largest thing a record can be missing and the least visible from inside
// it: a person notices a class ending, never that years went unrecorded.
func gapQuestion(g weave.Gap) Question {
	span := fmt.Sprintf("%s to %s", g.From.Format(monthLabel), g.To.Format(monthLabel))
	subject := "Your record"
	if g.Source != "" {
		subject = "Your " + g.Source
	}
	return Question{
		ID:   id(KindGap, g.Source+"|"+span),
		Kind: KindGap,
		Prompt: fmt.Sprintf("%s goes quiet for %s, from %s. What was happening then?",
			subject, approxMonths(g.Months*30), span),
		Context: fmt.Sprintf("%d entries across %d months, against about %.0f a month before and %.0f after.",
			g.Entries, g.Months, g.Before, g.After),
		When:   g.From,
		Weight: g.Months,
	}
}

// monthLabel renders a month as YYYY-MM.
const monthLabel = "2006-01"

// dateLayout renders a date as YYYY-MM-DD.
const dateLayout = "2006-01-02"

// id derives a stable short identifier for a question, so the same gap always
// produces the same key and an answered question is never asked again.
func id(kind Kind, subject string) string {
	if subject == "" {
		return ""
	}
	sum := sha256.Sum256([]byte(string(kind) + "\x00" + subject))
	return string(kind) + "-" + hex.EncodeToString(sum[:4])
}

// sortedKeys returns map keys in a stable order.
func sortedKeys(m map[string]string) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

// approxYears renders a day count as an approximate number of years or months.
func approxYears(days int) string {
	if days < 365 {
		return approxMonths(days)
	}
	return fmt.Sprintf("%.1f years", float64(days)/365)
}

// approxMonths renders a day count as an approximate number of months or days.
func approxMonths(days int) string {
	switch {
	case days < 45:
		return fmt.Sprintf("%d days", days)
	case days < 365:
		return fmt.Sprintf("%d months", days/30)
	}
	return fmt.Sprintf("%.1f years", float64(days)/365)
}
